name: Blog App

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: '12.x'

      - name: Install Dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Prettify
        run: yarn prettify
